### ISSUE TITLE
Seems broken with recent Vim

### ISSUE THREAD

**Issue by rhysd** [thinca/vim-themis#57]
## Environment

- Vim 8.1p950 (MacVim snapshot-155)
- macOS 10.12
- shell: zsh 5.2

<details>
<pre>
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:42)
macOS version
Included patches: 1-950
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +cryptv            +fork()            +modify_fname      +perl              +tag_old_static    +viminfo
+arabic            +cscope            +fullscreen        +mouse             +persistent_undo   -tag_any_white     +vreplace
+autocmd           +cursorbind        -gettext           +mouseshape        +postscript        +tcl               +wildignore
+autochdir         +cursorshape       -hangul_input      +mouse_dec         +printer           +termguicolors     +wildmenu
-autoservername    +dialog_con_gui    +iconv             -mouse_gpm         +profile           +terminal          +windows
+balloon_eval      +diff              +insert_expand     -mouse_jsbterm     -python            +terminfo          +writebackup
+balloon_eval_term +digraphs          +job               +mouse_netterm     +python3           +termresponse      -X11
+browse            +dnd               +jumplist          +mouse_sgr         +quickfix          +textobjects       -xfontset
++builtin_terms    -ebcdic            +keymap            -mouse_sysmouse    +reltime           +textprop          +xim
+byte_offset       +emacs_tags        +lambda            +mouse_urxvt       +rightleft         +timers            -xpm
+channel           +eval              +langmap           +mouse_xterm       +ruby              +title             -xsmp
+cindent           +ex_extra          +libcall           +multi_byte        +scrollbind        +toolbar           -xterm_clipboard
+clientserver      +extra_search      +linebreak         +multi_lang        +signs             +transparency      -xterm_save
+clipboard         -farsi             +lispindent        -mzscheme          +smartindent       +user_commands
+cmdline_compl     +file_in_path      +listcmds          +netbeans_intg     +startuptime       +vartabs
+cmdline_hist      +find_in_path      +localmap          +num64             +statusline        +vertsplit
+cmdline_info      +float             +lua               +odbeditor         -sun_workshop      +virtualedit
+comments          +folding           +menu              +packages          +syntax            +visual
+conceal           -footer            +mksession         +path_extra        +tag_binary        +visualextra
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_F
ORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L.             -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.
sdk/usr/local/libressl/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr
/local/lib -L.             -L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/us
r/local/libressl/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/local
/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit  -L/usr/local/opt/lua/lib -ll
ua5.3 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framew
ork/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framewo
rk CoreFoundation -framework Ruby
</pre>
</details>

## Repro

Clone vim-themis

```
git clone https://github.com/thinca/vim-themis.git
```

Save test case to file `foo.vimspec` as follows:

```vim
call themis#helper('command').with(themis#helper('assert'))

Describe test
    It should pass
        Assert 1
    End
End
```

And run the script as follows:

```
./vim-themis/bin/themis foo.vimspec
```

## Expected Behavior

It should output

```
1..1
ok 1 - test should pass

# tests 1
# passes 1
```

## Actual Behavior

But I got output

```
1o
##
```

Note: No newline after last `#`

## Investigation

I confirmed expected behavior with old Vim at `/usr/bin/vim` which is pre-installed in macOS. The version is `7.4p898` (actually patches are `1-898, 985, 8056` and I don't know what 8056 is).

<details>
<pre>
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul 31 2018 23:07:42)
Included patches: 1-898, 985, 8056
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             -farsi           -mouse_netterm   +syntax
-arabic          +file_in_path    -mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           -mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
+builtin_terms   -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         -gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    -keymap          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      -sniff           -xsmp
+eval            -mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv
</pre>
</details>

```
THEMIS_VIM=/usr/bin/vim ./vim-themis/bin/themis foo.vimspec
```

So I guess this is a regression issue with grow of Vim.

I also comfirmed expected behavior with Neovim. So this issue seems to occur with recent Vim only.

**Comment by thinca** [comment]
This is Vim's bug and already fixed at latest version.

**Comment by rhysd** [comment]
If you know, could you let me know which version fixed this issue? I need to add version check to my test case because the latest stable version of MacVim does not get the fix yet.

**Comment by thinca** [comment]
Maybe fixed here https://github.com/vim/vim/commit/97c2c05ead689f4a5de986c82531fcbd09295cda

**Comment by rhysd** [comment]
Sure. Thank you.

**Comment by kkoomen** [comment]
@thinca I am still having this issue in VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 18 2019 23:51:40)...

**Comment by thinca** [comment]
Please use Vim before 8.1.0917 or after v8.1.0969. This is Vim's bug so can't fix by plugin.

**Comment by kkoomen** [comment]
This is the output of `brew info vim`:

```
vim: stable 8.1.1350 (bottled), HEAD
Vi 'workalike' with many additional features
https://www.vim.org/
Conflicts with:
  ex-vi (because vim and ex-vi both install bin/ex and bin/view)
  macvim (because vim and macvim both install vi* binaries)
/usr/local/Cellar/vim/8.1.1350 (1,852 files, 31.0MB)
  Poured from bottle on 2019-05-26 at 11:23:07
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/vim.rb
==> Dependencies
Required: gettext ✔, lua ✔, perl ✔, python ✔, ruby ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 59,116 (30 days), 183,862 (90 days), 797,682 (365 days)
install_on_request: 54,402 (30 days), 168,781 (90 days), 709,098 (365 days)
build_error: 0 (30 days)
```

so this says 8.1.1350, then it should be good, right? because I still have the issue.

**Comment by thinca** [comment]
Your system may have other Vim.  Please check `vim --version`.

**Comment by kkoomen** [comment]
This is the output of `vim --version`:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 18 2019 23:51:40)
macOS version
Included patches: 1-950
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +textprop
++builtin_terms    -gettext           +num64             +timers
+byte_offset       -hangul_input      +odbeditor         +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +transparency
+clientserver      +job               +perl/dyn          +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua/dyn           +ruby/dyn          +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             -X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        -xpm
+emacs_tags        +mouse_dec         -sun_workshop      -xsmp
+eval              -mouse_gpm         +syntax            -xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE 
```

**Comment by thinca** [comment]
Your Vim on `$PATH` is v8.1.950.  This version contains the bug.

**Comment by kkoomen** [comment]
> Your Vim on $PATH is v8.1.0950. This version contains the bug.
How do you know that version?

Also, how can I use brew to downgrade specifically to that version?

**Comment by rhysd** [comment]
> How do you know that version?

From your output at https://github.com/thinca/vim-themis/issues/57#issuecomment-496006820

> Included patches: 1-950

I guess you installed both `vim` and `macvim` formulae. Please `brew uninstall macvim` or `brew unlink macvim`.

Anyway, this is not related to vim-themis so it's off-topic.

**Comment by kkoomen** [comment]
output of `brew uninstall macvim`
```
/usr/local/Cellar/macvim
```

output of `brew unlink macvim`
```
Error: No such keg: /usr/local/Cellar/macvim
```

output of `macvim`
```
-bash: macvim: command not found
```
